stages:
  - build

variables:
  IMAGE_NAME: test-image

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "Тестовый пайплайн запускается!"
    - docker --version
    - docker build -t $IMAGE_NAME .
